// Tier 1b: the offline food table (USDA SR Legacy, generated by scripts/build-foods.mjs).
// Pure search logic; runs inside a Web Worker (foodSearch.worker.ts) so typing stays instant.

import MiniSearch, { type Query } from 'minisearch';
import type { LogItem } from './types';

/** Compact row as stored in public/foods.json. Nutrition is per 100 g. */
export type FoodRow = [
  fdcId: number,
  display: string,
  name: string,
  category: number,
  kcal: number,
  protein_g: number,
  carbs_g: number,
  fat_g: number,
  fiber_g: number | null,
  portions: [label: string, grams: number][],
];

export interface FoodTableFile {
  source: string;
  categories: string[];
  foods: FoodRow[];
}

export interface FoodHit {
  fdcId: number;
  display: string;
  name: string;
  category: string;
  per100: { kcal: number; protein_g: number; carbs_g: number; fat_g: number; fiber_g: number | null };
  /** Household portions [label, grams], most common first. */
  portions: [string, number][];
}

// Common US names → words USDA uses. Each maps to extra phrasings; the original is always searched too.
export const SYNONYMS: Record<string, string[]> = {
  fries: ['french fried potato'],
  'french fries': ['french fried potato'],
  soda: ['cola'],
  pop: ['cola'],
  'soft drink': ['carbonated beverage'],
  coke: ['cola'],
  hoagie: ['submarine sandwich'],
  sub: ['submarine sandwich'],
  grinder: ['submarine sandwich'],
  hero: ['submarine sandwich'],
  chips: ['potato chips'],
  crisps: ['potato chips'],
  'hot dog': ['frankfurter'],
  hotdog: ['frankfurter'],
  ketchup: ['catsup'],
  burger: ['hamburger'],
  cheeseburger: ['cheeseburger', 'hamburger cheese'],
  donut: ['doughnut'],
  oatmeal: ['oats cereal', 'oats'],
  beer: ['alcoholic beverage beer'],
  bacon: ['pork cured bacon'],
  'mac and cheese': ['macaroni and cheese'],
  'mac n cheese': ['macaroni and cheese'],
  'mac & cheese': ['macaroni and cheese'],
  jello: ['gelatin dessert'],
  popsicle: ['frozen novelties ice'],
  'cool whip': ['whipped topping'],
  'lunch meat': ['luncheon meat'],
  'deli meat': ['luncheon meat'],
  'deli turkey': ['turkey breast luncheon'],
  cilantro: ['coriander'],
  oj: ['orange juice'],
  pb: ['peanut butter'],
  'saltine crackers': ['saltines'],
  jelly: ['jams preserves', 'jellies'],
  'string cheese': ['mozzarella string'],
  'half and half': ['half and half cream'],
  scallion: ['onions spring scallions'],
  garbanzo: ['chickpeas'],
  yam: ['sweet potato'],
};

const STOP = new Set(['and', 'with', 'of', 'the', 'a', 'an', 'in', 'or', 'on', 'n', '&']);

/** Lowercase, strip accents, drop stop words, and fold simple plurals so "apple" finds "Apples". */
export function processTerm(term: string): string | null {
  let t = term.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
  if (STOP.has(t)) return null;
  if (t.length > 4 && t.endsWith('ies')) t = t.slice(0, -3) + 'y';
  else if (t.length > 4 && t.endsWith('oes')) t = t.slice(0, -2);
  else if (t.length > 3 && t.endsWith('s') && !t.endsWith('ss') && !t.endsWith('us')) t = t.slice(0, -1);
  return t;
}

export function decode(file: FoodTableFile): FoodHit[] {
  return file.foods.map(([fdcId, display, name, cat, kcal, protein_g, carbs_g, fat_g, fiber_g, portions]) => ({
    fdcId, display, name, category: file.categories[cat] ?? 'Other',
    per100: { kcal, protein_g, carbs_g, fat_g, fiber_g },
    portions,
  }));
}

export interface FoodIndex {
  foods: FoodHit[];
  mini: MiniSearch<{ id: number; display: string; name: string; category: string }>;
}

export function buildIndex(foods: FoodHit[]): FoodIndex {
  const mini = new MiniSearch<{ id: number; display: string; name: string; category: string }>({
    fields: ['display', 'name', 'category'],
    idField: 'id',
    processTerm,
    searchOptions: { processTerm },
  });
  mini.addAll(foods.map((f, id) => ({ id, display: f.display, name: f.name, category: f.category })));
  return { foods, mini };
}

/** Query variants: the text as typed, plus each synonym substitution. */
export function expandQuery(q: string): string[] {
  const text = q.toLowerCase().trim();
  const out = new Set([text]);
  for (const [key, alts] of Object.entries(SYNONYMS)) {
    const re = new RegExp(`(^|\\s)${key.replace(/[.*+?^${}()|[\]\\&]/g, '\\$&')}(?=\\s|$)`);
    if (re.test(text)) for (const alt of alts) out.add(text.replace(re, `$1${alt}`));
  }
  return [...out];
}

const opts = {
  prefix: (term: string) => term.length > 2,
  fuzzy: (term: string) => (term.length > 4 ? 0.2 : term.length > 3 ? 1 : false),
  boost: { display: 3, name: 1, category: 0.3 },
};

// Everyday versions first. These only apply when the word isn't in what you typed,
// so searching "dried apples" or "imitation cheese" still finds them first.
const LESS_COMMON: [RegExp, number][] = [
  [/\bimitation\b/i, 0.5],
  [/\bindustrial\b/i, 0.4],
  [/\bproducer\b/i, 0.5],
  [/\bsubstitute\b/i, 0.6],
  [/\bmeatless\b/i, 0.6],
  [/\b(dried|dehydrated|powder|powdered|dry mix|sulfured)\b/i, 0.6],
  [/\bspecial dietary\b/i, 0.6],
  [/\bnon-carbonated\b/i, 0.6],
  [/\b(sheep|goat|human|buffalo|camel)\b/i, 0.6],
  [/\((alaska native|navajo|hopi|apache|shoshone|ojibwa|northern plains indians)\)/i, 0.6],
  [/\b(glutinous|unenriched)\b/i, 0.7],
  [/total can content/i, 0.7],
  [/\b(low|reduced)[ -]sodium\b|\bwithout salt\b|\bsalt not added\b/i, 0.8],
  [/\breduced fat\b/i, 0.85],
  [/\b(uncooked|unprepared)\b/i, 0.8],
  [/\bcanned entree\b/i, 0.8],
  [/\binstant\b/i, 0.85],
];
const EVERYDAY: [RegExp, number][] = [
  [/\bbrewed\b/i, 1.2],
  [/\bwhole\b/i, 1.15],
  [/\b(raw|fresh|cooked|plain|enriched)\b/i, 1.1],
  [/\bcommercially prepared\b/i, 1.1],
];
const BRAND = /\b[A-Z][A-Z'&]{2,}\b/; // CHOBANI, BURGER KING, SILK…

/** Relative weight of a query variant: synonyms are what USDA calls the thing you typed. */
const SYNONYM_WEIGHT = 2.5;

/**
 * Fuzzy, word-order-independent search. Every word must match (AND); if nothing does,
 * falls back to any-word (OR). Then everyday, simply-named foods are ranked up.
 */
export function searchFoods(index: FoodIndex, q: string, limit = 15): FoodHit[] {
  return searchFoodsDetailed(index, q, limit).results;
}

/** Like searchFoods, plus `loose`: true when no food had every word and these are any-word matches. */
export function searchFoodsDetailed(index: FoodIndex, q: string, limit = 15): { results: FoodHit[]; loose: boolean } {
  if (q.trim().length < 2) return { results: [], loose: false };
  const typed = q.toLowerCase();
  const variants = expandQuery(q);
  const typedTerms = new Set(variants.flatMap((v) => v.split(/[\s,]+/).map(processTerm).filter(Boolean) as string[]));

  const run = (combineWith: 'AND' | 'OR') => {
    const best = new Map<number, { score: number; terms: string[] }>();
    variants.forEach((v, i) => {
      const w = i === 0 ? 1 : SYNONYM_WEIGHT;
      for (const h of index.mini.search({ queries: [v], combineWith } as Query, opts)) {
        const s = h.score * w;
        const prev = best.get(h.id as number);
        if (!prev || s > prev.score) best.set(h.id as number, { score: s, terms: h.terms });
      }
    });
    return best;
  };
  let hits = run('AND');
  const loose = hits.size === 0;
  if (loose) hits = run('OR');

  const ranked = [...hits].map(([id, h]) => {
    const f = index.foods[id];
    let s = h.score;
    // USDA puts what the food *is* before the first comma ("Egg, whole" vs "Bagels, egg").
    const base = f.name.split(',')[0].split(/\s+/).map(processTerm).filter(Boolean) as string[];
    const exact = base.filter((w) => typedTerms.has(w)).length;
    s *= exact === base.length ? 1.6 : exact > 0 ? 1.2 : 1;
    for (const [re, m] of LESS_COMMON) if (re.test(f.name) && !re.test(typed)) s *= m;
    for (const [re, m] of EVERYDAY) if (re.test(f.name)) s *= m;
    const brand = f.name.match(BRAND)?.[0];
    if (brand && !typed.includes(brand.toLowerCase())) s *= 0.85;
    const words = f.name.split(/[\s,]+/).length;
    return { f, s: s / (1 + words * 0.04) };
  });
  ranked.sort((a, b) => b.s - a.s);
  return { results: ranked.slice(0, limit).map((r) => r.f), loose };
}

// ---------- serving math ----------

export function nutritionFor(food: FoodHit, grams: number) {
  const k = grams / 100;
  const r1 = (n: number) => Math.round(n * k * 10) / 10;
  return {
    kcal: Math.round(food.per100.kcal * k),
    protein_g: r1(food.per100.protein_g),
    carbs_g: r1(food.per100.carbs_g),
    fat_g: r1(food.per100.fat_g),
    fiber_g: food.per100.fiber_g === null ? null : r1(food.per100.fiber_g),
  };
}

/**
 * A log item for `count` × one household portion. Nutrition is stored per 1 portion and the
 * count is the multiplier, so the ½×–2× buttons keep working after it's added.
 * With `grams`, logs that weight instead (multiplier 1).
 */
export function foodItem(food: FoodHit, portion: [string, number], count: number, grams?: number): LogItem {
  const base = grams !== undefined ? { label: `${Math.round(grams)} g`, g: grams, mult: 1 } : { label: portion[0], g: portion[1], mult: count };
  return {
    name: food.display,
    portion: base.label,
    multiplier: base.mult,
    ...nutritionFor(food, base.g),
    source: 'usda',
    source_ref: `sr:${food.fdcId}`,
    confidence: null,
  };
}
